apiVersion: v1
kind: Secret
metadata:
  name: secrets-15soat-tech-challenge
type: Opaque
stringData:
  # App env var
  DB_NAME: ${DB_NAME}
  DB_USER: ${DB_USER}
  DB_PASSWORD: ${DB_PASSWORD}
  DB_HOST: 	${DB_HOST}
  DB_PORT: ${DB_PORT}
  JWT_SECRET: ${JWT_SECRET}
  # Potgres env var
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DB: ${POSTGRES_DB}
