apiVersion: v1
kind: Secret
metadata:
  name: secrets-15soat-tech-challenge
  namespace: soat-grupo76
type: Opaque
stringData:
  DB_PORT: ${DB_PORT}
  DB_HOST: 	${DB_HOST}
  POSTGRES_DB: ${POSTGRES_DB}
  POSTGRES_USER: ${POSTGRES_USER}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  JWT_SECRET: ${JWT_SECRET}
