export enum ServiceOrderStatus {
  APROVADO = 'APROVADO',
  CANCELADO = 'CANCELADO',
  ENTREGUE = 'ENTREGUE',
  PENDENTE = 'PENDENTE',
}

export enum RequestedServicesStatus {
  AGUARDANDO_APROVACAO = 'AGUARDANDO APROVAÇÃO',
  APROVADO = 'APROVADO',
  CANCELADO = 'CANCELADO',
  EM_DIAGNOSTICO = 'EM DIAGNÓSTICO',
  EM_EXECUCAO = 'EM EXECUÇÃO',
  ENTREGUE = 'ENTREGUE',
  FINALIZADA = 'FINALIZADA',
  RECEBIDA = 'RECEBIDA',
}
