export enum ServiceOrderStatus {
  APPROVED = 'APPROVED',
  CANCELED = 'CANCELED',
  FINALIZADA = 'FINALIZADA',
  PENDING = 'PENDING',
}

export enum RequestedServicesStatus {
  AGUARDANDO_APROVACAO = 'AGUARDANDO APROVAÇÃO',
  APPROVED = 'APPROVED',
  CANCELED = 'CANCELED',
  EM_DIAGNOSTICO = 'EM DIAGNÓSTICO',
  EM_EXECUCAO = 'EM EXECUÇÃO',
  ENTREGUE = 'ENTREGUE',
  FINALIZADA = 'FINALIZADA',
  RECEBIDA = 'RECEBIDA',
}
